// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umiokqaeizfgbqgjpslj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtaW9rcWFlaXpmZ2JxZ2pwc2xqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1Mjc5MzUsImV4cCI6MjA2ODEwMzkzNX0.bR5atKQqLmArPSt4jsDIWo0xzgtVQr90Wb4K-lDz6h8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});